Areas/Rent/Models/RentalItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TheatreCMS3.Areas.Rent.Models
{
    public class RentalItem
    {
        public int RentalItemId { get; set; }
        public string Item { get; set; }
        public string ItemDescription { get; set; }
        public DateTime PickupDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public Byte[] ItemPhoto { get; set; }

    }
}

Areas/Rent/Controllers/RentalItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Threading.Tasks;
using System.Web.Mvc;
using TheatreCMS3.Areas.Rent.Models;
using TheatreCMS3.Models;
using System.IO;
using System.Drawing;

namespace TheatreCMS3.Areas.Rent
{
    public class RentalItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rent/RentalItems
        public async Task<ActionResult> Index(string searchString)
        {
            var Rentals = from r in db.RentalItems
                          select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                Rentals = Rentals.Where(s => s.Item.Contains(searchString) || s.ItemDescription.Contains(searchString));
            }
            return View(await Rentals.ToListAsync());
        }

        // GET: Rent/RentalItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalItem rentalItem = db.RentalItems.Find(id);
            if (rentalItem == null)
            {
                return HttpNotFound();
            }
            return View(rentalItem);
        }

        // GET: Rent/RentalItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rent/RentalItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RentalItemId,Item,ItemDescription,PickupDate,ReturnDate,ItemPhoto")] RentalItem rentalItem, HttpPostedFileBase userimage)
        {
            if (ModelState.IsValid)
            {

                db.RentalItems.Add(rentalItem);
                db.SaveChanges(); 
                return RedirectToAction("Index");
            }

            return View(rentalItem);
        }

        // GET: Rent/RentalItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalItem rentalItem = db.RentalItems.Find(id);
            if (rentalItem == null)
            {
                return HttpNotFound();
            }
            //creating a temporary 
            TempData["image"] = rentalItem;

            return View(rentalItem);
            
        }

        // POST: Rent/RentalItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RentalItemId,Item,ItemDescription,PickupDate,ReturnDate,ItemPhoto")] RentalItem rentalItem, HttpPostedFileBase userimage)
        {
            //instanating a temporary object of class RentalItem to ensure that when form is submitted, either the original image is saved along with the form, or a new image is uploaded depending on user request.
            //If original image byte array is null, we find the rental item to later save. If the image field is not empty,  we save the template of the instantiated object to later update.
            RentalItem orginalimg = TempData["image"] == null ? db.RentalItems.Find(rentalItem.RentalItemId) : (RentalItem)TempData["image"];
            if (ModelState.IsValid)
            {

                if (userimage != null)
                {
                    var updateimage = rentalimage(userimage);
                    rentalItem.ItemPhoto = updateimage;
                }

                if (userimage == null && rentalItem.ItemPhoto == null && orginalimg.ItemPhoto != null)
                {
                    rentalItem.ItemPhoto = orginalimg.ItemPhoto;
                }

                db.Entry(rentalItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rentalItem);
        }

        // GET: Rent/RentalItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalItem rentalItem = db.RentalItems.Find(id);
            if (rentalItem == null)
            {
                return HttpNotFound();
            }
            return View(rentalItem);
        }

        // POST: Rent/RentalItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RentalItem rentalItem = db.RentalItems.Find(id);
            db.RentalItems.Remove(rentalItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //public byte[] RentalImg(HttpPostedFileBase userimage)
        //{
        //    byte[] imgArray;
        //    using (BinaryReader reader = new BinaryReader(userimage.InputStream))
        //    {
        //        imgArray = reader.ReadBytes(userimage.ContentLength);
        //    }
        //    return imgArray;
        //}

        [HttpPost]
        public byte[] rentalimage(HttpPostedFileBase userimage)
        {
            byte[] fileByte = new byte[userimage.ContentLength];
            userimage.InputStream.Read(fileByte, 0, userimage.ContentLength);
            return fileByte;
        }


    }
}

Areas/Rent/Views/RentalItems/Create.cshtml
@model TheatreCMS3.Areas.Rent.Models.RentalItem

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="RentalItem-create--header">Create Rental Item</h2>


@using (Html.BeginForm("Create", "RentalItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal rentalItem-create--form">
        <h4>Rental</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Item, "Rental Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox", placeholder = @Html.DisplayNameFor(m => m.Item) } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox", placeholder = @Html.DisplayNameFor(m => m.ItemDescription) } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PickupDate, "Pickup Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupDate, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox", placeholder = @Html.DisplayNameFor(m => m.PickupDate) } })
                @Html.ValidationMessageFor(model => model.PickupDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDate, "Return Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox", placeholder = @Html.DisplayNameFor(m => m.ReturnDate) } })
                @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:flex; flex-direction: column; align-items: center;">
            @Html.LabelFor(model => model.ItemPhoto, "Rental Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="file" name="userimage" id="userimage" onchange="loadFile(event)" style="margin-bottom: .75rem;"/>
            <img id="output" style="cursor:pointer; display: none;" height="350" width="250"/>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemPhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 RentalItem-create--createbutton">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 RentalItem-create--backbutton">
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Rent/Views/RentalItems/Delete.cshtml
@model TheatreCMS3.Areas.Rent.Models.RentalItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string image = "";
    if (Model.ItemPhoto != null)
    {
        image = Convert.ToBase64String(Model.ItemPhoto);
    }
    string deletelink = Url.Action("Delete", "RentalItems", new { id = Model.RentalItemId });
    string backlink = Url.Action("", "RentalItems");
}
<h2>Delete</h2>

<h3 style="text-align: center;">Are you sure you want to delete @Html.DisplayFor(model => model.Item) from the Rental List? </h3>
<div>

    <div class="RentalItem-detail-detailbody">
        <div class="RentalItem-details--container">
            <div class="RentalItem-details--image">
                <img src="data:image/jpg;base64,@image" height="1500" />
                <div class="RentalItem-detail-buttons">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div>
                            <button class="RentalItem-detail--backbutton RentalItem-detail--1" type="submit">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                                Delete
                            </button>
                        </div>
                        <div>
                            <button class="RentalItem-detail--backbutton RentalItem-detail--2" type="button" onclick="location.href='@backlink'">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                Back to List
                            </button>
                        </div>
                    }

                </div>

            </div>
            <div class="RentalItem-details--info">
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Pickup Date:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.PickupDate)
                    </div>
                </div>
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Return Date:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.ReturnDate)
                    </div>
                </div>
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Description:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.ItemDescription)
                    </div>
                </div>


            </div>
        </div>
    </div>

    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Item)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Item)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ItemDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemDescription)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PickupDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PickupDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReturnDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ItemPhoto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemPhoto)
            </dd>

        </dl>*@

    @*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }*@
</div>

Areas/Rent/Views/RentalItems/Details.cshtml
@model TheatreCMS3.Areas.Rent.Models.RentalItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string image = "";
    if (Model.ItemPhoto != null)
    {
        image = Convert.ToBase64String(Model.ItemPhoto);
    }
    string editlink = Url.Action("Edit", "RentalItems", new { id = Model.RentalItemId });
    string backlink = Url.Action("", "RentalItems");
}

<div>
    <h4 style="font-weight: bold; color: var(--secondary-color); text-align: center; margin-top: 2rem;">@Html.DisplayFor(model => model.Item)</h4>
    <hr />

    <div class="RentalItem-detail-detailbody">
        <div class="RentalItem-details--container">
            <div class="RentalItem-details--image">
                <img src="data:image/jpg;base64,@image" height="1500" />
                <div class="RentalItem-detail-buttons">
                    <div>
                        <button class="RentalItem-detail--backbutton RentalItem-detail--1" type="button" onclick="location.href='@editlink'">
                            <i style="" class="fa fa-file" aria-hidden="true"></i>
                            Edit
                        </button>
                    </div>
                    <div>
                        <button class="RentalItem-detail--backbutton RentalItem-detail--2" type="button" onclick="location.href='@backlink'">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            Back to List
                        </button>
                    </div>
                </div>

            </div>
            <div class="RentalItem-details--info">
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Pickup Date:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.PickupDate)
                    </div>
                </div>
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Return Date:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.ReturnDate)
                    </div>
                </div>
                <div class="RentalItem-details--infocontent">
                    <div class="RentalItem-details--infolabel">
                        Description:
                    </div>
                    <div class="RentalItem-details--infoinfo">
                        @Html.DisplayFor(model => model.ItemDescription)
                    </div>
                </div>


            </div>
        </div>
    </div>


    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Item)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Item)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ItemDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemDescription)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PickupDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PickupDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReturnDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ItemPhoto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemPhoto)
            </dd>

        </dl>*@
</div>
@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.RentalItemId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

Areas/Rent/Views/RentalItems/Edit.cshtml
@model TheatreCMS3.Areas.Rent.Models.RentalItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="RentalItem-create--header">Edit Rental</h2>


@using (Html.BeginForm("Edit", "RentalItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    string image = "";
    if (Model.ItemPhoto != null)
    {
        image = Convert.ToBase64String(Model.ItemPhoto);
    }
    <div class="form-horizontal rentalItem-create--form">
        <h4>Rental</h4>


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RentalItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.Item, "Rental Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox" } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PickupDate, "Pickup Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupDate, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox" } })
                @Html.ValidationMessageFor(model => model.PickupDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDate, "Return Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control RentalItem-create--inputbox" } })
                @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemPhoto, "Rental Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="file" name="userimage" id="userimage" />
            <img src="data:image/jpg;base64,@image" height="250" width="250" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 RentalItem-create--createbutton">
                <input type="submit" value="Save" class="btn btn-default " />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 RentalItem-create--backbutton">
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>

    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Rent/Views/RentalItems/Index.cshtml
@model IEnumerable<TheatreCMS3.Areas.Rent.Models.RentalItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-top: 2rem;">Index</h2>



    <div class="form-group">
        <button onclick="location.href ='/Rent/RentalItems/Create'" class="col-md-offset-2 col-md-10" style="width: 22%;">
            Create New
        </button>
    </div>

    <form asp-controller="RentalItems" asp-action="Index">
        <p>
            Search: &nbsp;<input style="background-color: var(--secondary-color); border: none; border-radius: .25rem; color: var(--light-color); padding: .25rem;" type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>

    @*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PickupDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemPhoto)
            </th>
            <th></th>
        </tr>*@



    @foreach (var item in Model)
    {


        string image = "";
        if (item.ItemPhoto != null)
        {
            image = Convert.ToBase64String(item.ItemPhoto);
        }
        string editlink = Url.Action("Edit", "RentalItems", new { id = item.RentalItemId });
        string detaillink = Url.Action("Details", "RentalItems", new { id = item.RentalItemId });
        string deletelink = Url.Action("Delete", "RentalItems", new { id = item.RentalItemId });
        <div class="RentalItem-index--cardcontainer">
            <div class="card RentalItem-index--cards" style="background-image: url(data:image/jpg;base64,@image); background-size: 100% 100%;">
                <div class="RentalItem-index-details">
                    <div onclick="location.href='@detaillink'">
                        <div class="RentalItem-index-detailinfo" height="100">@Html.DisplayFor(modelItem => item.ItemDescription)</div>

                        <div>@Html.DisplayFor(modelItem => item.PickupDate)</div>
                    </div>
                    <div class="RentalItem-index--buttoncontainer">
                        <div class="RentalItem-index--buttons" onclick="location.href='@editlink'">
                            <div>
                                <i class="fa fa-file" aria-hidden="true"></i>
                            </div>
                            <div>
                                Edit
                            </div>
                        </div>

                        <div class="RentalItem-index--buttons" onclick="location.href='@detaillink'">
                            <div>
                                <i class="fa fa-info-circle" aria-hidden="true"></i>

                            </div>
                            <div>
                                Details
                            </div>
                        </div>

                        <div class="RentalItem-index--buttons" onclick="location.href='@deletelink'">
                            <div>
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </div>
                            <div>
                                Delete
                            </div>
                        </div>

                        @*@Html.ActionLink("Edit", "Edit", new { id = item.RentalItemId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.RentalItemId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.RentalItemId })*@
                    </div>

                </div>
            </div>
            <div style="text-align: center;">@Html.DisplayFor(modelItem => item.Item)</div>
        </div>

    @*<tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PickupDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                <img src="data:image/jpg;base64,@image" height="100" width="100" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RentalItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.RentalItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RentalItemId })
            </td>
        </tr>*@
}

@*</table>*@